### ISSUE TITLE
FullAuto Highway Builder

### ISSUE THREAD

**Issue by Sightem** [ionar2/spidermod#309]
What I am trying to say is something that places e-chests, mines them, and places the obsidian according to your configured settings. note that I have tried to find something like this on this github and on Baritone itself, but i could not find what i was looking for

I have tried to find something like this on this github and on Baritone itself, but i could not find what i was looking for

**Comment by graemeg** [comment]
This is probably what you are looking for then. We are customising/extending Baritone with highway building functionality. It can already dig and pave in all 8 directions. It can auto-disconnect on damage, find pickaxes or obsidian in shulkers, mine up echests for obsidian, replace (save) pickaxes before they break. It will even eat a gapple before mining a block leading to lava.

https://github.com/mankool0/baritone/tree/highwayBuilding

Run: `./gradlew build`
then load up the custom Baritone api-forge version into your MC.
